# .streamlit/secrets.toml 파일 내용
[naver_api]
AD_API_KEY = "01000000006e38ce6fa90e4ff5f87791d9902b056c88dfb0bf9c353c7edb3d75daa4eaa580"
AD_SECRET_KEY = "AQAAAABuOM5vqQ5P9fh3kdmQKwVsXg23PEjQF+dc0opa9oYo6A=="
AD_CUSTOMER_ID = "2035977"
DATALAB_CLIENT_ID = "NxTASJSJpz0P320SPVLy"
DATALAB_CLIENT_SECRET = "gizA7Qc2iQ"